---
version: "3.5"
services:
  localstack:
    image: localstack/localstack:2.3.2
    environment:
      - SERVICES=s3
      - REGION=eu-central-1
      - DEFAULT_REGION=eu-central-1
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - ./scripts/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh
      - localstack-data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 4566:4566

volumes:
  localstack-data: {}
